# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTeach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Question_feature',
            field=models.CharField(default='hard|fifth', max_length=30),
            preserve_default=False,
        ),
    ]
