# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTeach', '0002_question_question_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Question_feature',
            field=models.CharField(max_length=50),
        ),
    ]
