# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTeach', '0005_auto_20170729_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Question_label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
