# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTeach', '0006_auto_20170729_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='Paper_id',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='Paper_marks',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='Paper_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='Paper_range',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
