# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTeach', '0007_auto_20170731_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionpaper',
            old_name='Paper_range',
            new_name='Paper_teacher_id',
        ),
    ]
